CREATE TABLE `candidato` (
  `ID_CANDIDATO` int NOT NULL,
  `NOME` varchar(200) NOT NULL,
  `CPF` varchar(14) NOT NULL,
  `RG` varchar(12) NOT NULL,
  `DATA_NASCIMENTO` date NOT NULL,
  `SEXO` varchar(20) NOT NULL,
  `MAE` varchar(200) NOT NULL,
  `PAI` varchar(200) NOT NULL,
  `ID_EMAIL` int NOT NULL,
  `ID_ENDERECO` int NOT NULL,
  `ALTURA` decimal(5,2) NOT NULL,
  `PESO` decimal(5,2) NOT NULL,
  `TIPO_SANGUINEO` varchar(3) NOT NULL,
  `ID_TELEFONE` int DEFAULT NULL,
  `ID_CELULAR` int DEFAULT NULL,
  PRIMARY KEY (`ID_CANDIDATO`),
  KEY `ID_EMAIL_idx` (`ID_EMAIL`),
  KEY `ID_ENDERECO_idx` (`ID_ENDERECO`),
  KEY `ID_TELEFONE_idx` (`ID_TELEFONE`),
  KEY `ID_CELULAR_idx` (`ID_CELULAR`),
  CONSTRAINT `ID_CELULAR` FOREIGN KEY (`ID_CELULAR`) REFERENCES `celular` (`ID_CELULAR`),
  CONSTRAINT `ID_EMAIL` FOREIGN KEY (`ID_EMAIL`) REFERENCES `email` (`ID_EMAIL`),
  CONSTRAINT `ID_ENDERECO` FOREIGN KEY (`ID_ENDERECO`) REFERENCES `endereco` (`ID_ENDERECO`),
  CONSTRAINT `ID_TELEFONE` FOREIGN KEY (`ID_TELEFONE`) REFERENCES `telefone` (`ID_TELEFONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `celular` (
  `ID_CELULAR` int NOT NULL,
  `CELULAR` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`ID_CELULAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cidade` (
  `ID_CIDADE` int NOT NULL,
  `CIDADE` varchar(200) NOT NULL,
  `ID_ESTADO` int NOT NULL,
  PRIMARY KEY (`ID_CIDADE`),
  KEY `ID_ESTADO_idx` (`ID_ESTADO`),
  CONSTRAINT `ID_ESTADO` FOREIGN KEY (`ID_ESTADO`) REFERENCES `estado` (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `email` (
  `ID_EMAIL` int NOT NULL,
  `EMAIL` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`ID_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `endereco` (
  `ID_ENDERECO` int NOT NULL,
  `CEP` varchar(10) NOT NULL,
  `LOGRADOURO` varchar(200) NOT NULL,
  `NUMERO` int NOT NULL,
  `BAIRRO` varchar(200) NOT NULL,
  `ID_CIDADE` int NOT NULL,
  PRIMARY KEY (`ID_ENDERECO`),
  KEY `ID_CIDADE_idx` (`ID_CIDADE`),
  CONSTRAINT `ID_CIDADE` FOREIGN KEY (`ID_CIDADE`) REFERENCES `cidade` (`ID_CIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `estado` (
  `ID_ESTADO` int NOT NULL,
  `ESTADO` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `telefone` (
  `ID_TELEFONE` int NOT NULL,
  `TELEFONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID_TELEFONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
